# Information
discordLink: https://discord.gg/brEcvy7A7y

# Response Options
announcementPrefix: "âš "

# Response Colors (using Adventure api)
chatColor: green
accentColor: yellow
errorColor: red

# Other Options
ignoreHostsInCommands: true
spawnWarp: spectate # Used for places like rejoins

# Scoreboard

# Random announcements
randomAnnouncementsEnabled: true
randomAnnouncementFrequency: 10m
randomAnnouncements:
  - Join our Discord in /discord!
  - This server uses EvientsCore, check it out in /credits!
  - Hide other players with /hide!
  - Check how many wins you have with /wins!
